### ISSUE TITLE
Initial Setup for Visa Direct - Two-Way SSL Connectivity

### ISSUE THREAD

**Issue by MauricioJr** [VisaDeveloperProgram/SampleCode#9]
Hello I'm trying to make my setup for Visa Direct API. The steps below it's not so clear to me.
```
Replace "{put the path to the keystore file here}" with the path to the keystore file
Replace "{put the keystore password}" with the path to the keystore password
Replace "{put the private key password here}" with the private key password
Run VisaDirectClient.java
You should see response from the VisaDirect API call
```
Checking the doc I was able to figure out they are related with Two-Way SSL Connectivity. 

What I did so far:
- I Downloaded these files: VDPCA-SBX.pem and key_myApp.pem 
- I checked the link vdpguide#gettingStarted and executed some OpenSSL commands using my  key_myApp.pem as base to create myapp_keyAndCertBundle.p12 and certreq.csr.

Is that possible to offer an example of how to generate the  Keystore password, private key password and Keystore file?

Using my /my/path/to/myapp_keyAndCertBundle.p12 as KEY_STORE_PATH and the offered pwd during
`openssl req -new -keyout` I'm getting:
```
Exception in thread "main" java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:653)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:225)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.apache.http.ssl.SSLContextBuilder.loadKeyMaterial(SSLContextBuilder.java:222)
	at org.apache.http.ssl.SSLContextBuilder.loadKeyMaterial(SSLContextBuilder.java:233)
	at com.visa.vdp.api.client.VisaDirectClient.main(VisaDirectClient.java:44)
```

Thank you in advance!

**Comment by MauricioJr** [comment]
I'm starting to use the default Certificate during this test phase.
Thanks

**Comment by VisaDeveloperProgram** [comment]
@MauricioJr Thanks for reaching out. Do let us know if you need any more help in this regard.

**Comment by AlbertMau** [comment]
I need help for same problem.

ı can't use these command;

keytool -importkeystore -srckeystore myapp_keyAndCertBundle.p12 -srcstoretype PKCS12 -destkeystore clientkeystore.jks
![image](https://user-images.githubusercontent.com/42492315/44298818-e3a7a400-a2f2-11e8-9f13-b477538a8fb4.png)
